### ISSUE TITLE
Build command work - assume instructions aren't quite right?

### ISSUE THREAD

**Issue by gmorph** [Meumeu/ZephyrusBling#10]
I've cloned the repo and followed the build instructions but get the following.  I assume I'm doing something simple wrong but I did follow the instructions to the letter.

ZephyrusBling/build(master)$ cmake .. --build
CMake Error: The source directory "/home/grant/projects/ZephyrusBling/build/--build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

Thanks, Grant.

**Comment by Meumeu** [comment]
You're right, the instructions are wrong, try `cmake ..` and then `cmake --build .` (or `cmake ..` and `make`)

**Comment by gmorph** [comment]
So I tried the following:

ZephyrusBling(master)$ cd build
ZephyrusBling/build(master)$ cmake ..
CMake Error at /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file:
  /home/davis/www/vcpkg/scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by Meumeu** [comment]
I don't use vcpkg, if you are using another fork can you clone from my repo and try again?

**Comment by gmorph** [comment]
ZephyrusBling(master)$ git remote -v
origin	https://github.com/Meumeu/ZephyrusBling.git (fetch)
origin	https://github.com/Meumeu/ZephyrusBling.git (push)

However just in case I complete removed the directory and cloned your repo again and now its working.  Its a pain to build under Ubuntu 20.10.  Had to download and build lots of repo's as no default packages for libraries are available.  Arch is definitely easier.

**Comment by gmorph** [comment]
Any Ubuntu users who want to be able to build this I did the following to make it work.

sudo apt install libfmt-dev libglm-dev libgsl-dev libboost-all-dev

git clone https://github.com/CLIUtils/CLI11
cd CLI11/
mkdir build
cd build
git submodule update --init
cmake ..
cmake --build . -j 10
sudo cmake --install .

git clone https://github.com/microsoft/GSL.git
cd GSL/
mkdir build
cd build
cmake ..
cmake --build . -j 10
sudo cmake --install .

curl -L -O https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.tar.gz
sudo mkdir /usr/share/fonts/TTF
tar -zxvf Hack-v3.003-ttf.tar.gz 
sudo mv ttf/* /usr/share/fonts/TTF
