### ISSUE TITLE
Can't compiling on Fresh Fedora 33

### ISSUE THREAD

**Issue by Mundo-Dev0ps** [Meumeu/ZephyrusBling#11]
Hello, 

I want to use but i get this error using command "cmake .. --build"

![image](https://user-images.githubusercontent.com/47090182/110220073-12ca9480-7ea2-11eb-93eb-7d7697317277.png)

Can anyone help me o I miss something?
Regards

**Comment by kingardor** [comment]
`cmake .. -B build`

**Comment by Meumeu** [comment]
The instructions in the README are wrong, I've just fixed them: you have to run `cmake ..` and `cmake --build . -j 10` instead of `cmake .. --build`

**Comment by Mundo-Dev0ps** [comment]
Hello @Meumeu and @aj-ames  

Thanks for answer

I get this error message using "cmake .." command
![image](https://user-images.githubusercontent.com/47090182/110220362-ea439a00-7ea3-11eb-9332-22ff2345cf66.png)

And using "cmake .. -B build" command
![image](https://user-images.githubusercontent.com/47090182/110220407-532b1200-7ea4-11eb-9353-b41c0287f2c4.png)

Log file is:
![image](https://user-images.githubusercontent.com/47090182/110220369-fa5b7980-7ea3-11eb-923c-264c2c8b3226.png)

Regards

**Comment by Meumeu** [comment]
I don't use Fedora so I can't test it on my machine, but you can try installing the following packages: boost-devel, cli11-devel, fmt-devel, glm-devel, guidelines-support-library, sdbus-cpp-devel

**Comment by Mundo-Dev0ps** [comment]
Hi @Meumeu ,

I can compilate after installing packages

Testing on Fedora is: 
```bash
sudo dnf install boost-devel cli11-devel fmt-devel glm-devel guidelines-support-library-devel sdbus-cpp-devel libasan libubsan -y
```
With commands
```bash
cmake ..
cmake --build . -j 10 
```
![image](https://user-images.githubusercontent.com/47090182/110221627-09462a00-7eac-11eb-9cbf-9bb1c56fb94f.png)

![image](https://user-images.githubusercontent.com/47090182/110221650-3266ba80-7eac-11eb-8cd3-b473ca2d64fd.png)

So Thanks :D 

Reggards
