### ISSUE TITLE
Error: Display text not work

### ISSUE THREAD

**Issue by Mundo-Dev0ps** [Meumeu/ZephyrusBling#12]
Hello everyone,

I get this error only with option `--text` 
![image](https://user-images.githubusercontent.com/47090182/113493628-7226bf00-94b7-11eb-9aa5-8e10b3fc4cfe.png)

Can anyone help me?
Regards

**Comment by finalclass** [comment]
@Mundo-Dev0ps install this [AUR](https://archlinux.org/packages/extra/any/ttf-hack/)
also check: https://github.com/Meumeu/ZephyrusBling/issues/7
