### ISSUE TITLE
What version of asus-nb-ctrl is required?

### ISSUE THREAD

**Issue by guysoft** [Meumeu/ZephyrusBling#14]
Undocumented which version of asus-nb-ctrl is required.

**Comment by haonanq666** [comment]
Any version, this used to use rog-core, which was a predecessor to asus-nb-ctrl (actually I think fluke is renaming it again now), so if you have asus-nb-ctrl installed it should work. Although I would suggest having the latest version anyways because there are more features.

**Comment by guysoft** [comment]
@haonanq666 Using the last 2.x version, because 3.x does not compile, they are also noting in the readme that the Animatrix is being reworked there
