### ISSUE TITLE
Not rendering with asus-nb-ctrl

### ISSUE THREAD

**Issue by haonanq666** [Meumeu/ZephyrusBling#2]
I installed and ran everything without any errors, but copy and pasting the demo commands to render the tux.png does not work (i.e. no image on back). The output says "Bling /org/meumeu/blings/4 created" without sign of error. Text throws errors but I suspect it is because I do not have fonts installed properly. The output:

`[org.meumeu.bling.CreateTextError] Error rendering text: convert: unable to read font '/usr/share/fonts/TTF/Hack-Regular.ttf' @ warning/annotate.c/RenderType/964.
`

Now I suspect it could be because I am running asus-nb-ctrl instead of rog-core, but the gitlab page for asus-nb-ctrl seems to suggest that AnimeMatrix function is supported and links to this very repository.  

Sorry if I am missing something obvious.

**Comment by Meumeu** [comment]
I haven't tried asus-nb-ctrl yet but it's the new name of rog-core so it should work unless the API changed.

For the text error you can try another font with the `--font` option.

**Comment by haonanq666** [comment]
Thanks for replying!
So I am kinda of a noob at systems in general so quite honestly I am not even sure I am running everything correctly. Thus far here is what i have done to set up:
Installed asus-nb-ctrl
installed imagemagick 
installed ZephyrusBling by cloning this repository and running cmake
ran "asusctl anime --on"
ran "build/.zephyrusblingd"
All the above ran without errors outputted to terminal. 
However still the tux.png just won't display. Please do let me know if you would like me to run anything for debug output.

**Comment by haonanq666** [comment]
Just an update on my tinkering. I reverted asus-nb-ctrl to rog-core and AnimeMatrix function works. I could not get it to work with asus-nb-ctrl. Since rog-core is deprecated, I would suggest that the functionality be updated (as the page for asus-nb-ctrl seems to have assumed it should work, the API likely did not change much). However, thanks anyways for allowing this functionality happen on linux, merci!

**Comment by Baldomo** [comment]
If you want the functionality now, check out my fork/PR for a fully working anime support with asusctl

**Comment by Meumeu** [comment]
@haonanq666 : it works now, thanks to @Baldomo

**Comment by haonanq666** [comment]
@Baldomo Yes I got it working, thanks a lot! Glad that it is now all merged into main repository.

A quick question: does ```zephyrusbling``` write anything to disk (i.e. use disk space)? I'm not quite sure what ```/org/meumeu/bling/#``` refers to, is it a file? Should I be reusing it instead of repeatedly running the ```./zephyrusbling --image [...]```?

**Comment by Baldomo** [comment]
A "bling" is a single image/text with associated effects (rotation, scale etc, including animations). Every bling is stored *in memory* (so no files on disk have to be interacted with) inside the daemon (see [here](https://github.com/Meumeu/ZephyrusBling/blob/a0c47d1adc049a820fb1f0ae713aca598dcb2921/BlingDaemon.cpp#L51) and [here](https://github.com/Meumeu/ZephyrusBling/blob/a0c47d1adc049a820fb1f0ae713aca598dcb2921/BlingDaemon.cpp#L77)). Moreover, each bling [has an id](https://github.com/Meumeu/ZephyrusBling/blob/a0c47d1adc049a820fb1f0ae713aca598dcb2921/Bling.h#L123), which gets printed as `#` in `/org/meumeu/bling/#` when you create a bling with `zephyrusbling <options>`. The CLI app adds it to the list by sending a DBus call to the daemon, which creates a call to `asusctl` (through DBus again) with arguments of the right format (byte arrays). `asusctl` then shows the image data on the anime display. The id system implies that you can actually make the daemon show a previously created bling, in this case sending a DBus method call to `zephyrusblingd` (to the method `org.meumeu.blingdaemon.Show`) as defined [here](https://github.com/Meumeu/ZephyrusBling/blob/a0c47d1adc049a820fb1f0ae713aca598dcb2921/dbus/OrgMeumeuBlingAdaptor.h#L40-L48). Hope this is clear enough, sorry if it's too concise.

**Comment by haonanq666** [comment]
It was a very clear explanation. As I really am not that proficient in Linux systems overall, I couldn't make sense of the source code; your explanation helped understand what is going on under the hood. So it creates a bling to memory, which is then displayed through ```asusctl```. If I run it continuously, are older blings removed from memory? Such as when I run  ```watch ./zephyrusbling <options>``` for an extended period of time, I see blings numbered into the thousands; would this unnecessarily hog memory? 

Sorry if the questions are trivial. Also, I know hardly anything about DBus so I can only understand "sending a DBus method call"  on a very high and abstracted level (but would not be able to figure out how to actually implement it).

**Comment by Meumeu** [comment]
Yes, they are deleted when they are not displayed anymore (see [here](https://github.com/Meumeu/ZephyrusBling/blob/master/BlingDaemon.cpp#L174-L177)).
