### ISSUE TITLE
[Feature Suggestion] Install hack-regular.ttf as a dependency of zephyrusbling

### ISSUE THREAD

**Issue by haonanq666** [Meumeu/ZephyrusBling#7]
Since this is the default font, it makes sense to install it automatically along with zephyrusbling (if possible, that is).

**Comment by gmorph** [comment]
curl -L -O https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.tar.gz
sudo mkdir /usr/share/fonts/TTF
tar -zxvf Hack-v3.003-ttf.tar.gz
sudo mv ttf/* /usr/share/fonts/TTF
