### ISSUE TITLE
Weird boost dependency

### ISSUE THREAD

**Issue by haonanq666** [Meumeu/ZephyrusBling#8]
I am on arch linux. After updating today, ```zephyrusblingd``` returns the error 
```
zephyrusblingd: error while loading shared libraries: libboost_filesystem.so.1.74.0: cannot open shared object file: No such file or directory

```
My boost version is now ```1.75.0```, which is probably the cause. However, after downgrading boost, my desktop environment totally stopped working basically, so I must use the latest version; therefore, I suggest that instead of depending on ```boost=1.74```, perhaps make the dependency ```boost>=1.74```.

**Comment by Meumeu** [comment]
There is no dependency on a particular version of Boost in the sources, but when you compile zephyrusblingd it links with the version that was installed at the time. You can just recompile zephyrusblingd after upgrading Boost, it will use the latest version.

**Comment by haonanq666** [comment]
Thanks, I downloaded from AUR so I thought I could just run makepkg again... turns out that I needed to delete the installation package I had locally as it defaulted to re-installing that. Now running makepkg again fixes the issue.
